project:
  type: website
  output-dir: docs

website:
  title: "Bash Esssentials"
  navbar:
    left:
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
  revealjs:
    output-ext: "slides.html"
    controls: true
    controls-tutorial: true
    logo: media/nd_logo.png
    transition: slide
    slide-number: true

resources:
    - code/*.sh
    - figures/*/*.png


