---
title: "For Loops: Iterations and Nesting"
author: Nathan M. Muncy
date: today
execute:
    freeze: auto
    # echo: true
format:
  revealjs:
    footer: "Bash Basics: for loops"
    logo: ../../media/nd_logo.png
    transition: slide
    slide-number: true
engine: knitr
---

## Purpose

:::: {style="font-size: 65%;"}
- **Knowledge**: Build loops and nested loops
- **Skill**:
    - Anatomy of for loop
    - Thinking in iterations
    - Nesting logic
- **Why**:
    - Apply same set of commands multiple times
    - e.g. pipeline step for each subject
::::

## What is a For Loop

:::::: columns
::::: {style="font-size: 65%;"}
:::: {.column width="50%"}
- Purpose of computing: get computers to do the work
- Computers are great at repeating work
    - Same command for different variables
    - Same workflow for different subjects
- Benefits: replicability, efficiency, reduce programmer typing
- For loops: special syntax to repeat series of commands
- Nate's Adage: Be clever
    - If repeating work, get computer to do it
    - Not lazy, efficient (without tendonitis)!
::::
:::: {.column width="\"50%"}
```{mermaid}
flowchart TB
  A[Start of list] --> B(Execute commands)
  B --> C{End of list?}
  C --> A
  C --> D[Exit]
```
::::
:::::
::::::

## Anatomy of For Loops

:::::: columns
::::: {.column width="50%"}
:::: {style="font-size: 65%;"}
- For loops have a specific structure:
    - Space separated '`for` variable `in` list'
    - New line `do`, series of commands
    - Reference variable with `$`
    - New line `done`
- Functionally:
    - Iterate through all items of list
    - Define variable from list for each iteration
    - Execute commands between `do` and `done` for each iteration
::::
:::::

::::: {.column width="\"50%"}
```{bash}
#| echo: true

for var in {1..3}; do
    echo $var
done
```
:::::
::::::::

## Iterating through lists

:::::: columns
::::: {.column width="50%"}
:::: {style="font-size: 65%;"}
- Possible to store lists
    - Use space between items
    - Account for bash returning space-separated output
- Reference list in for loop syntax by variable
- Best practices:
    - Add `do` to for loop definition line
        - ";" indicates End Of Line (EOL)
    - Indent to show logic levels
    - `done` on separate line, original indentation
::::
:::::

::::: {.column width="\"50%"}
```{bash}
#| echo: true
my_sent="i am great"
num_list=$(echo {1..3})
# file_list=$(ls .)
for var in $my_sent $num_list; do
    echo $var
done
```
:::::
::::::::

## Nesting For Loops

:::::: columns
::::: {.column width="50%"}
:::: {style="font-size: 65%;"}
- A child loop can exist within a parent loop
- **Entire** child loop executed for **each** parent loop iteration
::::
:::::

::::: {.column width="\"50%"}
```{bash}
#| echo: true
for num in {1..3}; do
    for alpha in {a..c}; do
        echo ${num}$alpha
    done
done
```
:::::
::::::::

## More Best Practices

:::::: columns
::::: {.column width="50%"}
:::: {style="font-size: 65%;"}
- Flatter is better
    - Limit nesting (logic) depth to ~3 levels
    - Try restructuring if deeper logic is needed
    - Be more clever
- Organize code into blocks
- Have meaningful variable names
    - `for i in {a..c} ...` vs
    - `for alpha in {a..c} ...`
::::
:::::

::::: {.column width="\"50%"}
```{bash}
#| echo: true
for num in {1..2}; do
    for alpha in {a..b}; do
        echo ${num}$alpha
    done
done
echo
for num_alpha in {1..2}{a..b}; do
    echo $num_alpha
done
```
:::::
::::::::
