---
title: "Conditionals: Exit status, square braces, special checks"
author: Nathan M. Muncy
date: today
execute:
    freeze: auto
    # echo: true
format:
  revealjs:
    footer: "Bash Basics: conditionals"
    logo: ../../media/nd_logo.png
    transition: slide
    slide-number: true
engine: knitr
---

## Purpose

:::: {style="font-size: 65%;"}
- **Knowledge**: Learn workflow control with dependencies
- **Skill**:
    - Using exit status values
    - Conditional statements
- **Why**:
    - Avoid rebuilding existing files: increases workflow speed, decreases CPU time
    - Control/account for different situations (multiple tasks, data types)
    - Validate output to avoid downstream errors
::::

## Exit Status

:::::: columns
::::: {.column width="50%"}
:::: {style="font-size: 65%;"}
- Every command returns an exit status
- Held on special variable `$?`
- `0`: command was successful
- `>0`: command was unsuccessful
    - Each number has specific meaning
::::
:::::

::::: {.column width="\"50%"}
```{bash}
#| echo: true
echo hi
echo $?
asdf
echo $?
```
:::::
::::::::

## Use Exit Status

:::::: columns
::::: {.column width="50%"}
:::: {style="font-size: 65%;"}
- Special commands `&&` and `||` evaluate `$?`
- `&&` listens for exit status `0`
    - if `0` (success) then process continues
- `||` listens for exit status `>0`
    - if `>0` (fail) the process continues
- Can be combined
- Keep these simple!
::::
:::::

::::: {.column width="\"50%"}
```{bash}
#| echo: true
echo hi && echo pass || echo fail
asdf && echo pass || echo fail
```
:::::
::::::::

## Square Braces

:::::: columns
::::: {.column width="50%"}
:::: {style="font-size: 65%;"}
- Square braces '`[]`' evaluate an internal statement to set exit status
- Internal exit status `0`: external exit status `0`
- Internal exit status `>0`:  external exit status `1`
- White space (spaces) is very important!
::::
:::::

::::: {.column width="\"50%" style="font-size: 80%;"}
```{bash}
#| echo: true
[ 1 == 1 ] && echo true || echo false
[ 1 == 2 ] && echo true || echo false
[ a == a ] && echo pass $? || echo fail $?
[ a == b ] && echo pass $? || echo fail $?
```
:::::
::::::::

## Conditionals: if

:::::: columns
::::: {.column width="50%"}
:::: {style="font-size: 65%;"}
- Conditional syntax utilize square braces for workflow control
    - i.e. execute commands only if a condition is met
- Syntax structure:
    - `if [ assertion ]`
    - New line `then`
    - Commands
    - New line `fi` to close conditional
- Conditional work only executed `if` exit status = `0`
::::
:::::

::::: {.column width="\"50%" style="font-size: 80%;"}
```{bash}
#| echo: true
if [ 1 == 1 ]; then
    echo Yay
fi
if [ 1 == 2 ]; then
    echo Nay
fi
```

::::{style="font-size: 65%;"}
::: incremental
- Why is `==` used and not `=`?
:::
::::
:::::
::::::::

## Conditionals: elif

:::::: columns
::::: {.column width="50%"}
:::: {style="font-size: 65%;"}
- Ability to capture workflow if first conditional fails
- `elif` (else if) assessed only when `if` exit status = `1`
- An entire new conditional is written
- Read conditionals top -> bottom
- Multiple `elif` statements allowed
::::
:::::

::::: {.column width="\"50%" style="font-size: 80%;"}
```{bash}
#| echo: true
foo=bat
if [ $foo == bar ]; then
    echo foobar
elif [ $foo == baz ]; then
    echo foobaz
elif [ $foo == bat ]; then
    echo foobat
fi
```

::::{style="font-size: 65%;"}
::: incremental
- How many conditionals failed?
- What if `foo=baz`?
:::
::::
:::::
::::::::

## Conditionals: else

:::::: columns
::::: {.column width="50%"}
:::: {style="font-size: 65%;"}
- `else` catches all failed conditions
- Specified last
- Does not evaluate an assertion
::::
:::::

::::: {.column width="\"50%" style="font-size: 80%;"}
```{bash}
#| echo: true
foo=foo
if [ $foo == bar ]; then
    echo foobar
elif [ $foo == baz ]; then
    echo foobaz
elif [ $foo == bat ]; then
    echo foobat
else
    echo "Unrecognized value of foo"
fi
```
:::::
::::::::

## Conditionals: and

:::::: columns
::::: {.column width="50%"}
:::: {style="font-size: 65%;"}
- Multiple assertions can be combined with `&&`
- As before, `&&` only continues if exit status = `0`
    - So, all conditionals would need to be true
::::
:::::

::::: {.column width="\"50%" style="font-size: 80%;"}
```{bash}
#| echo: true
foo=bar
num=1
if [ $foo == bar ] && [ $num == 1 ]; then
    echo Success
fi
```

::::{style="font-size: 65%;"}
::: incremental
- Would `[ $num == 1 ]` be assessed if `foo=baz`?
:::
::::
:::::
::::::::

## Conditionals: or

:::::: columns
::::: {.column width="50%"}
:::: {style="font-size: 65%;"}
- Assertions can also be combined with `||`
- As before, `||` only continues if exit status `>0`
    - So, only one of the assertions needs to be true
- These can be combined with `&&`
::::
:::::

::::: {.column width="\"50%" style="font-size: 80%;"}
```{bash}
#| echo: true
alpha=a
num=1
if [ $alpha == b ] || [ $num == 1 ]; then
    echo Success
fi
```

::::{style="font-size: 65%;"}
::: incremental
- If the assertion was written `[ $alpha == a ]`, would `[ $num == 1 ]` have been assessed?
- Which of the assertions triggers the conditional in:
:::
::::
::::{.fragment}
```{bash}
#| echo: true
[ 1 == 2 ] && [ a == a ] || [ b == b ]
```
::::
:::::
::::::::

## Conditionals: not

:::::: columns
::::: {.column width="50%"}
:::: {style="font-size: 65%;"}
- The character `!` inverts logic
- `[ 1 != 0 ]`: true (`$?`=0)
- `[ ! 1 == 0 ]`: true (`$?`=0)
- Note the white space in the second assertion
- Useful to name variables to help reader through logic
::::
:::::

::::: {.column width="\"50%"}
```{bash}
#| echo: true
[ a != b ] && echo $?
[ ! foo == bar ] && echo $?
```
::::{style="font-size: 65%;"}
::: incremental
- What is printed in:
:::
::::
::::{.fragment}
```{bash}
#| echo: true
#| eval: false
[ ! foo == bar ] && echo alpha \
    || echo beta
[ foo == bar ] || [ ! 1 == 2 ] \
    && echo delta || echo gamma
```
::::
:::::
::::::::

## Comparing integers

:::::: columns
::::: {.column width="50%"}
:::: {style="font-size: 65%;"}
- A set of special comparators operators for integers
    - `-gt`: greater than
    - `-lt`: less than
    - `-ge`: greater than or equal
    - `-le`: less than or equal
    - `-eq`: equal
    - `-ne`: not equal
- Note: double parentheses are used for mathematic expressions (>, <, <=, etc)
    - `(( 1 <= 2 ))`
- See more details [here](http://mywiki.wooledge.org/BashFAQ/031)
::::
:::::

::::: {.column width="\"50%"}
```{bash}
#| echo: true
[ 1 -lt 2 ] && echo 1 $?
[ ! 1 -gt 2 ] && echo 2 $?
[ 1 -le 2 ] && echo 3 $?
[ ! 1 -ge 2 ] && echo 4 $?
```
::::{style="font-size: 65%;"}
::: incremental
- What is printed in:
:::
::::
::::{.fragment}
```{bash}
#| echo: true
#| eval: false
[ ! 1 -lt 2 ] && [ 1 -eq 1 ] \
    && echo alpha || echo beta
[ 1 -gt 2 ] || [ ! 1 -ge 2 ] \
    && echo delta || echo gamma
```
::::
:::::
::::::::

## File management

:::::: columns
::::: {.column width="50%"}
:::: {style="font-size: 65%;"}
- A set of special comparators operators for managing files
    - `-e`: something exists
    - `-d`: a directory exists
    - `-f`: a file exists
    - `-s`: a file contains data
    - `-z`: a variable is empty
::::
:::::

::::: {.column width="\"50%"}
```{bash}
#| echo: true
#| eval: false
[ -f foo.txt ]
[ -e foobar ]
[ -d my_dir ]
[ -z $foo ]
```
::::{style="font-size: 65%;"}
::: incremental
- What is printed in:
:::
::::
::::{.fragment}
```{bash}
#| echo: true
#| eval: false
echo "foo" > my_file.txt
[ ! -s my_file.txt ] \
    && echo alpha || echo beta
```
::::
:::::
::::::::

## Best practices

:::::: columns
::::: {.column width="50%"}
:::: {style="font-size: 65%;"}
- Keep conditionals below 3 levels of logic:
    - Simple, flat, short
- Consider breaking up long chains into multiple statements
- Inverting logic often simplifies
- Name variables to help through logic
    - `is_empty`: holds boolean of whether file is empty
    - `file_exists`: holds boolean of whether file exists
::::
:::::

::::: {.fragment .column width="\"50%" style="font-size: 65%;"}
```{bash}
#| echo: true
#| eval: false
# Flight control with variable
foo=""
foo_empty=$([ -z $foo ] && echo $? || echo $?)
[ $foo_empty == 0 ] && echo set_var || echo move_on

# Flight control with file
touch foo.txt
foo_exists=$([ -f foo.txt ] && echo $? || echo $?)
[ $foo_exists == 0 ] && echo move_on || echo make_foo
```
::: incremental
- What would be printed in the examples above?
:::
:::::
::::::::